services:
  api:
    build:
      context: .
      dockerfile: server/Dockerfile

    container_name: flowdesk-api-container

    environment:
      MONGOMS_VERSION: "7.0.14"
      MONGOMS_DISTRO: "ubuntu-22.04"
      BULLMQ_REDIS_URL: redis://redis:6379

    env_file:
      - server/.env

    ports:
      - "3001:3001"

    command: npm run dev

    volumes:
      - ./server:/app/server
      - ./shared:/app/shared
      - /app/server/node_modules

  notification-worker:
    build:
      context: .
      dockerfile: server/Dockerfile

    container_name: flowdesk-notification-worker-container

    environment:
      BULLMQ_REDIS_URL: redis://redis:6379

    env_file:
      - server/.env

    command: npm run worker:notifications:dev

    volumes:
      - ./server:/app/server
      - ./shared:/app/shared
      - /app/server/node_modules

    depends_on:
      - redis

  client:
    build:
      context: .
      dockerfile: client/Dockerfile

    container_name: flowdesk-client-container

    ports:
      - "5173:5173"

    command: npm run dev -- --host 0.0.0.0

    volumes:
      - ./client:/app/client
      - ./shared:/app/shared
      - /app/client/node_modules

  redis:
    image: redis:7-alpine
    container_name: flowdesk-redis-container
    ports:
      - "6379:6379"
